### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by edysegura** [ricardo-faria/Ricardo-PayCheck#1]
There is no validation to avoid call the server if the user didn't input any salary.

![image](https://cloud.githubusercontent.com/assets/5324414/10769681/5a8b29e6-7cce-11e5-8b14-3d60e89efeb3.png)

**Comment by ricardo-faria** [comment]
the bug was fixed.

**Comment by edysegura** [comment]
Great!! Keep it going! Its the only way to mastering anything!
